### PR TITLE
feat: Afterpay payment method

### PR DESCRIPTION
**Pull request by gabrielelpidio**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **main branch** (left side). Also you should start _your branch_ off _our main_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Description

- Adds afterpay components to the library
- Adds docs for afterpay components

🧡 Thank you!

### CODE REVIEW

**Comment by danestves** [comment]
Maybe you have pushed duplicated folders? I'm seeing `__docs__` and `stories` folders with the same content

**Review by danestves — CHANGES_REQUESTED** [review]
You have two folders `__docs__` and `stories`, we must only use the `__docs__` to avoid be bundled on npm

**Comment by gabrielelpidio** [comment]
@danestves the `stories` folder just contains the components that will be used in each story. This is done just to separate the files into different folders to avoid having too much files into one folder. It doesn't seem to affect the build output, and what is being publish should only be the dist folder

Let me know what you think of this approach.

**Comment by danestves** [comment]
Alright, didn't see that the folder structure are inside `__docs__` looks nice to me

**Review by danestves — APPROVED** [review]

**Pull request merged**
